version: '3.8'

services:
  app:
    build: .
    container_name: recsys2025
    env_file:
      - .env
    volumes:
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]